name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      - uses: arduino/setup-protoc@master
        with:
          version: '3.13.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: go version
      - run: go env
      - run: protoc --version

      - run: export PATH=$(go env GOPATH)/bin:${PATH}
      - run: go get -u github.com/golang/protobuf/protoc-gen-go

      - run: make test
