name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
      - uses: arduino/setup-protoc@master
        with:
          version: '3.19.4'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: go version
      - run: go env
      - run: protoc --version
      - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - run: make test
